name: weather_app
description: "A Weather Mobile App (Flutter)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^0.13.6
  geolocator: ^9.0.2
  flutter_local_notifications: ^12.0.4
  url_launcher: ^6.1.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  
